### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by AI-Gardener** [AI-Gardener/Pezzza-s-pendulum#1]
# ROADMAP
- [x] AI reinforcement training
- [ ] GPU AI reinforcement training
- [x] AI network serde
- [x] Display of the physics system
- [ ] Display of the network
    - [ ] In/Hidden/Out distinct node colors
    - [ ] Values => colored inner disks?
    - [ ] Connections
- [ ] Display both together
- [ ] Instanced rendering or so, to see several agents at the same time
- [ ] Display the score below each instance
- [x] Saving a rendering to video

## EDIT
Use Godot Extension Rust for rendering.  
Roadmap to be made.
